### ISSUE TITLE
basestring is not supported in python 3

### ISSUE THREAD

**Issue by sujittiwari** [gettalent/one-signal-python-sdk#9]
While trying to use it with python 3 getting following issue
` File "D:\frejun\frejun_backend\vEnv\lib\site-packages\onesignalsdk\one_signal_sdk.py", line 50, in __init__
    assert isinstance(version, basestring), 'version is not valid'
NameError: name 'basestring' is not defined`

A faster fix for this could be
`try:
    unicode = unicode
except NameError:
    # 'unicode' is undefined, must be Python 3
    str = str
    unicode = str
    bytes = bytes
    basestring = (str,bytes)
else:
    # 'unicode' exists, must be Python 2
    str = str
    unicode = unicode
    bytes = str
    basestring = basestring`

That is what I am using in my project.

**Comment by sujittiwari** [comment]
Should I fork and raise a pull request?

**Comment by mzohaibqc** [comment]
Hi @sujittiwari ,

I am main contributor to this SDK but now I don't have access to this repo. Also, this repo is not being maintained by anyone. I've forked this and added support for Python3. You can install by adding this line in `requirements.txt`.
> git+https://github.com:mzohaibqc/one-signal-python-sdk.git@master

**Comment by sujittiwari** [comment]
I will see 

thanks
